### ISSUE TITLE
More liaisons with W3C groups or external organizations?

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-star-wg-charter#10]
Idea of external organization:
- groups involved in PG standardization? (e.g. https://ldbcouncil.org/gql-community/pgswg/)

**Comment by domel** [comment]
:+1: As a member of the PGSWG, I strongly support it.
It is also worth paying attention to ISO/IEC CD 39075 https://www.iso.org/standard/76120.html and ISO/IEC CD 9075-16.2 https://www.iso.org/standard/79473.html

**Comment by TallTed** [comment]
For clarity of communication, ISO/IEC CD 39075 is "Information Technology — Database Languages — GQL", and ISO/IEC CD 9075-16.2 "Information technology — Database languages SQL — Part 16: SQL Property Graph Queries (SQL/PGQ)".  Of course, so far as I know, neither of these specs will be readable without purchase, and being ISO docs, they are not likely to be cheap.  The degree of attention I and others may be able to pay to them is therefore likely to be limited.

**Comment by gatemezing** [comment]
IMHO, something like a joint W3C-ISO/PGSWG project would be a good idea. How to phase it? see an example with OGC for the Spatial Data on the Web Working Group Charter, https://www.w3.org/2015/spatial/charter#coordination

**Comment by domel** [comment]
> Of course, so far as I know, neither of these specs will be readable without purchase, and being ISO docs, they are not likely to be cheap. The degree of attention I and others may be able to pay to them is therefore likely to be limited.

LDBC (and PGSWG) has ISO SC32 WG3 formal liaison.

**Comment by TallTed** [comment]
In my experience, formal liaison does not necessarily mean we get (access to) copies of relevant specs. Working toward such sharing would be helpful.

**Comment by domel** [comment]
LDBC members have access to that copies.

**Comment by afs** [comment]
Thank you @TallTed for highlighting this issue.

All,

What does "liason" cover?

W3C operates open processes with public review and comment.
How can this fit with W3C Working Group Process with public review and comment?

How can this fit with W3C Patent Policy?
https://www.w3.org/Consortium/Patent-Policy-20200915/

OGC has a specific collaboration with W3C. It took time to set it up.

**Comment by domel** [comment]
ISO has three types of liaisons: A, B, and C. C is the best option. More information you can find on https://www.sae.org/works/committeeResources.do?resourceID=784893
I think that time is a bigger issue. Both GQL and SQL/PGQ are at a fairly advanced stage. It seems to me that it will be easier to establish cooperation with PGSWG and LDBC. Which indirectly allows us to keep our finger on the pulse when it comes to ISO standards.

**Comment by afs** [comment]
@domel - that talks about "technical contributions and participate fully in the work of a [ISO] WG".

What is the agenda of the liason? Shared work? Does it fit with the desired timescales of a W3C WG or the ISO WGs?

It sounds like there may be interesting discussions though not restricted to the work proposed in this W3C WG charter.
(in the before-times: a joint workshop)

**Comment by pchampin** [comment]
FTR, W3C has a type C liaison with ISO JTC1/SC 32 [1]. The contact person is @iherman .
[1] https://www.w3.org/2001/11/StdLiaison#ISO

**Comment by afs** [comment]
Scoped to XML and Dublin Core.

So it is a person, not a WG?

It would be good for the semantic web community to have a liaison with other organisations.

**Comment by pchampin** [comment]
> Scoped to XML and Dublin Core.

Yes. Must have been a while :stuck_out_tongue: 

> So it is a person, not a WG?

The way I see it, W3C liaison are here to ease the communication between specific WGs on both sides.

> It would be good for the semantic web community to have a liaison with other organisations.

FTR, I recently set up [a liaison with DDI-Alliance](https://www.w3.org/2001/11/StdLiaison#DDI-Alliance)

**Comment by domel** [comment]
If I remember correctly, GQL is planned for the second half of 2023, and SQL/PGQ is planned for the first half of 2023.

**Comment by pchampin** [comment]
this was discussed during today's call
