### ISSUE TITLE
Include RDFa Core 1.2 as a normative specification to deliver

### ISSUE THREAD

**Issue by csarven** [w3c/rdf-star-wg-charter#19]
This is a proposal to include RDFa Core 1.2 as a normative specification in the charter that the WG should deliver.

I've reviewed what I believe to me most relevant minutes that touches on RDFa: https://w3c.github.io/rdf-star/Minutes/2021-12-17.html#x141 however it is unclear to me as to why RDFa 1.2 is not listed as one of the work items alongside the other [concrete RDF syntaxes](https://www.w3.org/TR/rdf11-concepts/#dfn-concrete-rdf-syntax) [rdf11-concepts] as a deliverable.

Are there technical, political or other barriers for this?

RDFa 1.0 and 1.1 are widely adopted. I believe is important to "upgrade" all concrete RDF syntaxes for uniform use going forward. There is - I for one - interest in contributing to the development of RDFa Core 1.2.

**Comment by gkellogg** [comment]
If you have some proposed syntax for adding either or both of quoted triples and annotated triples to RDFa, we can certainly discuss here, or charter a new RDFa CG.

**Comment by pchampin** [comment]
this was discussed during today's call: https://w3c.github.io/rdf-star/Minutes/2022-03-04.html#x152

**Comment by afs** [comment]
I hope we get a proposal from the RDFa community; that's the only barrier AFAIK.

There's a provision for adding more documents in the lifetime of the proposed working group already in the charter. CSVW falls into that category as well.

**Comment by csarven** [comment]
We can put a proposal for RDFa 1.2 that:
* addresses [RDFa 1.1 Errata](https://www.w3.org/2001/sw/wiki/RDFa_1.1._Errata)
* includes [Multiple Graphs in RDFa (“RDFa Quads”)](http://buzzword.org.uk/2009/rdfa4/spec);
* introduces RDFa-star.
* ?

If I understand correctly, this work can be done through the existing RDF-DEV CG or with the formation of the RDFa CG.

---

From the past discussions, I understand that the charter can be updated to include RDFa at a later date and that the inclusion of some of the syntaxes was arbitrary. I'd suggest that either RDFa is added or RDF/XML is removed from the Charter - based on rough reading of the room. Having said that, I don't have an objection to keep the Charter as is - I do believe the group is approaching this in good faith.

**Comment by pchampin** [comment]
> I understand that the charter can be updated to include RDFa at a later date 

yes

> and that the inclusion of some of the syntaxes was arbitrary.

no quite. We simply included all specs produced by the previous RDF and SPARQL WGs, leaving aside all specs produced by other WGs.

**Comment by afs** [comment]
About: “RDFa Quads”:

The scope in the charter is "RDF-star + errata" in order to present a charter to W3C that is bounded. [Section 1](https://w3c.github.io/rdf-star-wg-charter/#scope).

I have no opinion one way or the other on "RDFa Quads" but if we add one extra feature, the argument for not accepting other features on other documents is made weaker.

Section 1.1 (out of scope) recognizes this:
"""
Adding other improvements or extensions to RDF or SPARQL. Given the number of recommendations that this Working Group needs to update, it is important to keep its scope very focused.
"""

**Comment by gkellogg** [comment]
RDFa 1.2, and many other specs may be useful to look at after a WG is chartered by the core mission, and when time and interest are apparent.

It would be good to create some issues in appropriate repositories that describe potential solutions for RDF-star, named graphs, and even directional text. Maybe in https://github.com/rdfa/rdfa.github.io.

**Comment by csarven** [comment]
Thanks all. I'm satisfied with the feedback and the direction to continue on this work.
