### ISSUE TITLE
Status of RDF/XML.

### ISSUE THREAD

**Issue by afs** [w3c/rdf-star-wg-charter#2]
The current (2021-09-03) draft text includes RDF/XML in the list "The Working Group will deliver the following W3C normative specifications:"

To date, there has been little effort on RDF/XML.

The charter might want to make this conditional: "The WG MAY revise RDF/XML ..."

There is a precedence here. There is no RDF/XML extension for RDF Datasets mainly, as I recall, due to lack of enthusiasm.

**Comment by pchampin** [comment]
this was discussed during today's meeting: https://w3c.github.io/rdf-star/Minutes/2021-11-12.html#x124

**Comment by pchampin** [comment]
this was discussed during today's call: https://github.com/w3c/rdf-star-wg-charter/issues/2
