### ISSUE TITLE
WG practice

### ISSUE THREAD

**Issue by afs** [w3c/rdf-star-wg-charter#3]
(The current draft has some general placeholder text for Timeline and is not a specific proposal.)

We all have to accept that face-to-face meetings have an environmental travel cost.

I suggest that no implication of physical F2F meetings is included and the WG can decide.

Personally, I hope the working group will decide on remote-only.

**Comment by gkellogg** [comment]
Some groups definitely over-use the F2F process, and it does put a big burden on members, particularly those without a corporate sponsor.

But, when used sparingly, they can be very effective at getting a lot of progress in a short time. The key is preparation by chairs and presenters in advance.

**Comment by pchampin** [comment]
I agree with @gkellogg , but I also agree with @afs that we should leave it to the WG members to decide that.
