### ISSUE TITLE
"Expression of Support" should not be the only way to respond to a proposal for new W3C work

### ISSUE THREAD

**Issue by danbri** [w3c/rdf-star-wg-charter#34]
https://github.com/w3c/rdf-star-wg-charter/issues/new/choose

This comes off as a kind of "lobbying the W3C AC" move, or like those awful UI patterns where you get asked to either "Opt in!" or "Ask me later", without a "No thanks" pathway...

**Comment by pchampin** [comment]
> "Expression of Support" should not be the only way to respond to a proposal for new W3C work

What would be giving the impression that it is the *only* way  to respond?
Both the W3C Advisory Committee [1] and the community behind `semantic-web@w3.org` [2] were notified a little more than a month ago, and explicitly asked for feedback -- any kind of feedback. And we did not receive much, unfortunately.

Even now, the link you quote still gives access to two templates : one to express support, and one to raise any kind of issue (as you have noticed, obviously). So I think the comparison to UI anti-patterns is a little unfair.

[1] https://www.w3.org/mid/625538bd-0a1c-4d23-d249-f96f98eba324@w3.org
[2] https://lists.w3.org/Archives/Public/semantic-web/2022Mar/0048.html
