### ISSUE TITLE
Fano Ramparany from the Orange group supports the creation of the RDF-star working group

### ISSUE THREAD

**Issue by ramparany** [w3c/rdf-star-wg-charter#35]
Fano Ramparany from Orange supports the creation of the RDF-star working group as described in the proposed charter.

RDF-star is to our knowledge the most mature extension of RDF for annotating edges. We are looking forward to see RDF-star be part of the W3C semantic web technologies suite.

**Comment by pchampin** [comment]
thanks @ramparany . Could you please edit also the body of the issue (replacing the striked out "organization" by something meaningful...).

**Comment by ramparany** [comment]
Done :) (editing the body of the issue with a mobile phone was problematic. So I ended up editing it with my PC)

----- Mail original -----
De: "Pierre-Antoine Champin" ***@***.***>
À: "w3c/rdf-star-wg-charter" ***@***.***>
Cc: "ramparany" ***@***.***>, "Mention" ***@***.***>
Envoyé: Jeudi 5 Mai 2022 09:43:18
Objet: Re: [w3c/rdf-star-wg-charter] Fano Ramparany from the Orange group supports the creation of the RDF-star working group (Issue #35)





thanks @ramparany . Could you please edit also the body of the issue (replacing the striked out "organization" by something meaningful...).
