### ISSUE TITLE
Add a deliverable (WG note) about "added feature"

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-star-wg-charter#5]
There has been some discussion [1,2] on making RDF a "living standard" by leveraging the new W3C Process from 2021. The general consensus, as I see it is: why not, but be careful not to make RDF too unstable.
I believe that a subgroup of the WG would need to think about it and produce, early on, a WG note about how to deal with new features in an acceptable way.

What do others think about it?

[1] https://github.com/w3c/EasierRDF/issues/88
[2] https://lists.w3.org/Archives/Public/semantic-web/2021Sep/0006.html

**Comment by afs** [comment]
Agree - it is something to start early.

Looking at our (this group) RDF-star experience, there have been several ideas that seem reasonable but when we dig into the details find it invalidates existing usage. e.g. "old client-new server" for new MIME types.

With no perfect solution, we have to choose the way forward with compromise, and that needs time.
