### ISSUE TITLE
Should the WG only apply editorial errata

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-star-wg-charter#9]
See #8 
The idea is to explicitly restrict the scope to purely editorial errata.
The rationale is that substantial errata may derail the group to technical discussions not related to RDF-star.

**Comment by afs** [comment]
Good point that there is a risk that unrelated technical discussions may consume the energy of the WG.

"editorial" may be too strong - in the [SPARQL errata](https://www.w3.org/2013/sparql-errata) some e.g [errata-query-15](https://www.w3.org/2013/sparql-errata#errata-query-15) are not editorial. 

I'm not sure what the right language is; may be "editorial" is the best. An alternative style is to put in something that is a condition on the WG time spent.

**Comment by pchampin** [comment]
I think the management of such non-editorial errata should be marked out-of-scope by default. We could still
- address them through the rechartering "hook" mentioned [here](https://github.com/w3c/rdf-star-wg-charter/issues/6#issuecomment-986801681), or
- be deferred to a future WG, possibly using the "new feature" process.

**Comment by afs** [comment]
SPARQL 1.1 had words to the effect of "don't invalidate any existing SPARQL 1.0 usage".

[errata-query-15](https://www.w3.org/2013/sparql-errata#errata-query-15) might be an unusual case because it is in RDF 1.1 RDF Dataset and hence argue that it is "editorial alignment". The difference matters to JSON-LD.

**Comment by pchampin** [comment]
addressed by #8 and further changes
